// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjD2qOm9w37kIQUDJEmm4l1tOmVUvP8tU',
    appId: '1:303613709401:web:e0ed7c4500274115ef3548',
    messagingSenderId: '303613709401',
    projectId: 'alertmate-ede6d',
    authDomain: 'alertmate-ede6d.firebaseapp.com',
    storageBucket: 'alertmate-ede6d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ1tb7q85rv1mSe0mpTtlShGT8XQF3EYU',
    appId: '1:303613709401:android:fde23d95abccec98ef3548',
    messagingSenderId: '303613709401',
    projectId: 'alertmate-ede6d',
    storageBucket: 'alertmate-ede6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4nIyF3MHoMm0wwazbnwbKCKSro5xrZws',
    appId: '1:303613709401:ios:03e7062751930db6ef3548',
    messagingSenderId: '303613709401',
    projectId: 'alertmate-ede6d',
    storageBucket: 'alertmate-ede6d.firebasestorage.app',
    iosBundleId: 'com.example.alertMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4nIyF3MHoMm0wwazbnwbKCKSro5xrZws',
    appId: '1:303613709401:ios:03e7062751930db6ef3548',
    messagingSenderId: '303613709401',
    projectId: 'alertmate-ede6d',
    storageBucket: 'alertmate-ede6d.firebasestorage.app',
    iosBundleId: 'com.example.alertMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjD2qOm9w37kIQUDJEmm4l1tOmVUvP8tU',
    appId: '1:303613709401:web:5c65fa7d23bbc729ef3548',
    messagingSenderId: '303613709401',
    projectId: 'alertmate-ede6d',
    authDomain: 'alertmate-ede6d.firebaseapp.com',
    storageBucket: 'alertmate-ede6d.firebasestorage.app',
  );
}
